### ISSUE TITLE
Extend expressivity to allow ComplementOf

### ISSUE THREAD

**Issue by cmungall** [berkeleybop/class-expression#5]
Can be punted to a later milestone, just making sure it is tracked

http://www.w3.org/TR/owl2-syntax/#Complement_of_Class_Expressions

key would be `complement` for consistent naming with `union` etc

```
class_expression.complement = function(cls_expr){
    var ce = new class_expression();
    ce.as_complement(cls_expr);
    return ce;
};
```

as_complement:

```
 var expression = {
    'type': 'complement',
    'operand': cxpr.structure()
    };
```

**Comment by hdietze** [comment]
Use 'filler' as variable name for the class expression

**Comment by kltm** [comment]
So switch from Chris's "operand" to "filler"?

**Comment by hdietze** [comment]
yes

**Comment by cmungall** [comment]
its not my operand its the owlapi's! but filler is fine
